### ISSUE TITLE
broken recipe

### ISSUE THREAD

**Issue by 0Navis0** [teamauroramods/Fruitful-Forge#32]
```
[04:29:36] [Worker-Main-23/ERROR]: Couldn't read item tag list fruitful:gives_sustaining_long from fruitful:tags/items/gives_sustaining_long.json in data pack Fruitful-1.16.5-2.1.0.jar
com.google.gson.JsonSyntaxException: Missing values, expected to find a JsonArray
	at net.minecraft.util.JSONUtils.func_151214_t(SourceFile:425) ~[?:?]
	at net.minecraft.tags.ITag$Builder.func_232956_a_(ITag.java:105) ~[?:?]
	at net.minecraft.tags.TagCollectionReader.func_242223_a(SourceFile:60) [?:?]
	at net.minecraft.tags.TagCollectionReader$$Lambda$18203/2133310044.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```

**Comment by WenXin20** [comment]
I've noticed this too.
It's because the json file requires the `values` parameter as well as the `optional` parameter.
So instead of:
```
{
  "replace": false,
  "optional": [
    "environmental:apple_pie"
  ]
}
```
It should be:
```
{
  "replace": false,
  "values": [],
  "optional": [
    "environmental:apple_pie"
  ]
}
```

**Comment by Toshy0** [comment]
Where would i find the .json so i can edit this?

**Comment by frakier** [comment]
in the jar file /data/fruitful/tags/items/gives_sustaining_long.json
